/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.simulador.views;

import autonoma.simulador.exceptions.*;
import autonoma.simulador.models.Simulador;
import autonoma.simulador.models.Vehiculo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Carlos
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Vehiculo vehiculo;
    private int velocidad = 0;
    private int frenado;
    private int aceleracion;

    public VentanaPrincipal(Vehiculo vehiculo) {
        initComponents();
        
        this.vehiculo = vehiculo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnEncender = new javax.swing.JButton();
        btnAcelerar = new javax.swing.JButton();
        btnFrenar = new javax.swing.JButton();
        btnFrenarBruscamente = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        txtEstado = new javax.swing.JTextField();
        txtVelocidad = new javax.swing.JTextField();
        btnComponentes = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtAcelerar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFrenar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel7.setText("Simulador De Conduccion");
        jLabel7.setAlignmentX(1.0F);
        jLabel7.setAlignmentY(1.0F);
        jLabel7.setIconTextGap(7);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buenas 110 Km/h", "Bonitas 70 Km/h", "Baratas 50 Km/h" }));

        jLabel3.setText("Km");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3000 cc 220 Km/h", "2000 cc 160 Km/h", "1000 cc 100 Km/h", " " }));

        btnEncender.setBackground(new java.awt.Color(0, 255, 255));
        btnEncender.setText("Encender");
        btnEncender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEncenderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEncenderMouseEntered(evt);
            }
        });
        btnEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderActionPerformed(evt);
            }
        });

        btnAcelerar.setBackground(new java.awt.Color(51, 255, 0));
        btnAcelerar.setForeground(new java.awt.Color(255, 255, 255));
        btnAcelerar.setText("Acelerar");
        btnAcelerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcelerarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcelerarMouseEntered(evt);
            }
        });
        btnAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcelerarActionPerformed(evt);
            }
        });

        btnFrenar.setBackground(new java.awt.Color(255, 0, 0));
        btnFrenar.setForeground(new java.awt.Color(255, 255, 255));
        btnFrenar.setText("Frenar");
        btnFrenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFrenarMouseClicked(evt);
            }
        });
        btnFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrenarActionPerformed(evt);
            }
        });

        btnFrenarBruscamente.setBackground(new java.awt.Color(51, 0, 0));
        btnFrenarBruscamente.setForeground(new java.awt.Color(255, 255, 255));
        btnFrenarBruscamente.setText("Frenar bruscamente");
        btnFrenarBruscamente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFrenarBruscamenteMouseClicked(evt);
            }
        });
        btnFrenarBruscamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrenarBruscamenteActionPerformed(evt);
            }
        });

        btnApagar.setBackground(new java.awt.Color(0, 0, 0));
        btnApagar.setForeground(new java.awt.Color(255, 255, 255));
        btnApagar.setText("Apagar");
        btnApagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnApagarMouseClicked(evt);
            }
        });

        txtEstado.setText("Apagado");
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });

        txtVelocidad.setText("0 ");
        txtVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVelocidadActionPerformed(evt);
            }
        });

        btnComponentes.setBackground(new java.awt.Color(255, 51, 255));
        btnComponentes.setText("Componentes");
        btnComponentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComponentesMouseClicked(evt);
            }
        });

        jLabel5.setText("Velocidad Actual");

        jLabel6.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFrenar)
                        .addGap(18, 18, 18)
                        .addComponent(txtFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAcelerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFrenarBruscamente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 61, Short.MAX_VALUE)
                .addComponent(txtVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnComponentes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(48, 48, 48)
                        .addComponent(btnEncender, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(btnApagar))
                        .addGap(24, 24, 24))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel7))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnApagar)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnEncender))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAcelerar)
                            .addComponent(txtAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFrenar)
                            .addComponent(txtFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnFrenarBruscamente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncenderMouseClicked
       try
       {
        vehiculo.encender();
        txtEstado.setText("Prendido"); 
        JOptionPane.showMessageDialog(null, "El vehiculo esta prendido");
       }
       catch(VehiculoEncendidoException e)
       {
           JOptionPane.showMessageDialog(null, "No se puede prender un vehiculo que ya esta prendido");
       }
    }//GEN-LAST:event_btnEncenderMouseClicked

    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed
        
        
        
    }//GEN-LAST:event_btnEncenderActionPerformed

    private void btnAcelerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcelerarMouseClicked
       // Verifica si el motor está apagado
    if (!vehiculo.motor.isEncendido()) {
        JOptionPane.showMessageDialog(null, "No puedes acelerar un vehículo apagado");
    } else {
        try {
            // Verificar si el campo de aceleración está vacío
            if (txtAcelerar.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, ingresa un valor en el campo de aceleración.");
                return; // Salir del método si el campo está vacío
            }

            // Obtener el valor de aceleración del campo de texto
            int aceleracion = Integer.parseInt(txtAcelerar.getText());

            // Validar que la aceleración sea positiva
            if (aceleracion <= 0) {
                JOptionPane.showMessageDialog(null, "La aceleración debe ser un valor positivo");
                return;
            }

            // Actualizar la velocidad del vehículo sumando la aceleración
            velocidad += aceleracion;

            // Verificar si la velocidad supera un límite máximo (opcional)
            if (velocidad > 200) {  // Límite de velocidad de 200 km/h, ajustable según el simulador
                velocidad = 0;
                JOptionPane.showMessageDialog(null, "Has superado el limite del motor, El vehiculo se accidento");
            }

            // Llamar al método acelerar del objeto vehiculo
            vehiculo.acelerar(velocidad);

            // Actualizar el campo de texto que muestra la velocidad
            txtVelocidad.setText(String.valueOf(velocidad));

        } catch (NumberFormatException ex) {
            // Si el texto ingresado en txtAcelerar no es un número válido
            JOptionPane.showMessageDialog(null, "Por favor, ingresa un número válido en el campo de aceleración.");
        } catch (VehiculoApagadoBloqueadoException ex) {
            // Manejo de la excepción si el vehículo no debería poder acelerar
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnAcelerarMouseClicked

    private void btnAcelerarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcelerarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAcelerarMouseEntered

    private void btnAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcelerarActionPerformed
        
    }//GEN-LAST:event_btnAcelerarActionPerformed

    private void btnFrenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFrenarMouseClicked
    // Verifica si el motor está apagado
    if (!vehiculo.motor.isEncendido()) {
        JOptionPane.showMessageDialog(null, "No puedes frenar un vehículo apagado");
    } else {
        try {
            // Obtener el valor de frenar del campo de texto (puede ser txtFrenar en lugar de txtAcelerar)
            int frenar = Integer.parseInt(txtFrenar.getText());

            // Verificar que la frenada no haga que la velocidad sea negativa
            if (frenar > velocidad) {
                JOptionPane.showMessageDialog(null, "El vehículo ha patinado, al frenar mas que la velocidad");
                    JOptionPane.showMessageDialog(null, "Se detuvo por completo el vehiculo, recuperando el control");
                velocidad = 0; // La velocidad no puede ser menor que 0
            } else {
                velocidad -= frenar; // Reducir la velocidad por el valor de frenado
            }

            // Llamar al método frenar del objeto vehiculo
            vehiculo.frenar(velocidad);

            // Actualizar el campo de texto que muestra la velocidad
            txtVelocidad.setText(String.valueOf(velocidad));

        } catch (NumberFormatException ex) {
            // Si el texto ingresado en txtFrenar no es un número válido
            JOptionPane.showMessageDialog(null, "Por favor, ingresa un número válido en el campo de frenado");
        } catch (VehiculoApagadoBloqueadoException ex) {
            // Manejo de la excepción si el vehiculo no debería poder frenar
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (VehiculoDetenidoException ex) {
            // Manejo de excepción si el vehiculo ya está detenido
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "El vehículo ya está detenido.");
        } catch (VehiculoPatinaraException ex) {
            // Manejo de excepción si el vehiculo patina
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Se patino");
        }
    }
    }//GEN-LAST:event_btnFrenarMouseClicked

    private void btnFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFrenarActionPerformed

    private void btnFrenarBruscamenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFrenarBruscamenteMouseClicked
        // se pondra el valor de la velocidad en 0
        txtVelocidad.setText("0");
        if (velocidad >= 100) {  
                velocidad = 100;
                JOptionPane.showMessageDialog(null, "Superado el limite de velocidad de las llantas al frenar, Vehiculo derrapado");
            txtVelocidad.setText("0");
            JOptionPane.showMessageDialog(null, "Se detuvo por completo el vehiculo, recuperando el control");
        }
    }//GEN-LAST:event_btnFrenarBruscamenteMouseClicked

    private void btnFrenarBruscamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrenarBruscamenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFrenarBruscamenteActionPerformed

    private void btnApagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApagarMouseClicked
        try
       {
        vehiculo.apagar();
        txtEstado.setText("Apagado"); 
        JOptionPane.showMessageDialog(null, "El vehiculo esta apagado");
       }
       catch(VehiculoApagadoException e)
       {
           JOptionPane.showMessageDialog(null, "No se puede apagar un vehiculo que ya esta apagado");
       } 
       catch (VehiculoAccidentadoException ex) 
       {
           JOptionPane.showMessageDialog(null, "Te accidentaste");
           txtVelocidad.setText("0");
       }
    }//GEN-LAST:event_btnApagarMouseClicked

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed

    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVelocidadActionPerformed

    }//GEN-LAST:event_txtVelocidadActionPerformed

    private void btnComponentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComponentesMouseClicked

    }//GEN-LAST:event_btnComponentesMouseClicked

    private void btnEncenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncenderMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEncenderMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcelerar;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnComponentes;
    private javax.swing.JButton btnEncender;
    private javax.swing.JButton btnFrenar;
    private javax.swing.JButton btnFrenarBruscamente;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAcelerar;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFrenar;
    private javax.swing.JTextField txtVelocidad;
    // End of variables declaration//GEN-END:variables
}
